using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Horizon.ERPAcc2.Permissions;
using Horizon.ERPAcc2.FiscalYearStatuses;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Horizon.ERPAcc2.Shared;

namespace Horizon.ERPAcc2.FiscalYearStatuses
{
    public class FiscalYearStatusesAppService : FiscalYearStatusesAppServiceBase, IFiscalYearStatusesAppService
    {
        //<suite-custom-code-autogenerated>
        public FiscalYearStatusesAppService(IFiscalYearStatusRepository fiscalYearStatusRepository, FiscalYearStatusManager fiscalYearStatusManager, IDistributedCache<FiscalYearStatusExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(fiscalYearStatusRepository, fiscalYearStatusManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}