using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Horizon.ERPAcc2.Permissions;
using Horizon.ERPAcc2.FiscalYearPeriods;

namespace Horizon.ERPAcc2.FiscalYearPeriods
{
    public class FiscalYearPeriodsAppService : FiscalYearPeriodsAppServiceBase, IFiscalYearPeriodsAppService
    {
        //<suite-custom-code-autogenerated>
        public FiscalYearPeriodsAppService(IFiscalYearPeriodRepository fiscalYearPeriodRepository, FiscalYearPeriodManager fiscalYearPeriodManager)
            : base(fiscalYearPeriodRepository, fiscalYearPeriodManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}