using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Horizon.ERPAcc2.FiscalYears
{
    public class FiscalYearManager : FiscalYearManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FiscalYearManager(IFiscalYearRepository fiscalYearRepository)
            : base(fiscalYearRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}