using Horizon.ERPAcc2.FiscalYearStatuses;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Horizon.ERPAcc2.FiscalYears
{
    public class FiscalYear : FiscalYearBase
    {
        //<suite-custom-code-autogenerated>
        protected FiscalYear()
        {

        }

        public FiscalYear(Guid id, int? fiscalYearStatusId, string fiscalYearName, DateTime startDate, DateTime endDate, int calanderYear, byte yearEndMonth, byte yearEndDay, bool isCurrent, bool isLocked, byte noOfPeriods, string periodInterval, DateTime? lockDate = null)
            : base(id, fiscalYearStatusId, fiscalYearName, startDate, endDate, calanderYear, yearEndMonth, yearEndDay, isCurrent, isLocked, noOfPeriods, periodInterval, lockDate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}