version: '3.7'

services:
  erpacc2-web:
    image: horizon/erpacc2-web:latest
    container_name: erpacc2-web
    hostname: erpacc2-web
    build:
      context: ../../
      dockerfile: src/Horizon.ERPAcc2.Web/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=25fcd6d8-5774-4a2b-9459-deb1da395c43
      - App__SelfUrl=https://localhost:44353
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://erpacc2-web
      - App__HealthCheckUrl=http://erpacc2-web/health-status      
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ERPAcc2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44353:443"
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  

  
  db-migrator:
    image: horizon/erpacc2-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/ERPAcc2.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__ERPAcc2_Web__RootUrl=https://localhost:44353
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=ERPAcc2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  sqldata:
    name: erpacc2_sqldata
networks:
  abp-network:
    name: erpacc2-network
    driver: bridge