using Horizon.ERPAcc2.FiscalYearStatuses;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Horizon.ERPAcc2.Permissions;
using Horizon.ERPAcc2.FiscalYears;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Horizon.ERPAcc2.Shared;

namespace Horizon.ERPAcc2.FiscalYears
{
    public class FiscalYearsAppService : FiscalYearsAppServiceBase, IFiscalYearsAppService
    {
        //<suite-custom-code-autogenerated>
        public FiscalYearsAppService(IFiscalYearRepository fiscalYearRepository, FiscalYearManager fiscalYearManager, IDistributedCache<FiscalYearExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<FiscalYearStatus, int> fiscalYearStatusRepository)
            : base(fiscalYearRepository, fiscalYearManager, excelDownloadTokenCache, fiscalYearStatusRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}