using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Horizon.ERPAcc2.FiscalYearStatuses
{
    public class FiscalYearStatusManager : FiscalYearStatusManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FiscalYearStatusManager(IFiscalYearStatusRepository fiscalYearStatusRepository)
            : base(fiscalYearStatusRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}