using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Horizon.ERPAcc2.FiscalYearPeriods
{
    public class FiscalYearPeriodManager : FiscalYearPeriodManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FiscalYearPeriodManager(IFiscalYearPeriodRepository fiscalYearPeriodRepository)
            : base(fiscalYearPeriodRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}